Support `Theme` attribute in `Code Block` macro
sphinx-contrib/confluencebuilder pull request #811
Opened 2023-05-27 03:51 UTC by bpandola

Closes #810

2023-05-27 16:11 UTC, jdknight requested changes
Brian, thanks for taking the time to making a pull request for this. Going to dump a series of review comments on if (mostly nitpicky stuff), if you do not mind address them ~ if not, I can help look at this a later time.

Aside from the review comments, the one thing I see missing is a configuration check entry for the new option. At minimum, we should have a check added to verify the string type of this configuration's value. For example, consider how `confluence_space_key` is [checked](https://github.com/sphinx-contrib/confluencebuilder/blob/v2.1.1/sphinxcontrib/confluencebuilder/config/checks.py#L706-L712).

Lastly, and completely optional, if you want to be extremely picky for the theme configuration option, you may even want to define a list of all acceptable theme types supported by Confluence (listing in somewhere in our ["Confluence standards" area](https://github.com/sphinx-contrib/confluencebuilder/blob/main/sphinxcontrib/confluencebuilder/std/confluence.py), and generate warnings if a user provides a theme that is not supported by Confluence. For sure not required; and if missing, will not block this pull request.

2023-05-27 21:52 UTC, bpandola commented on sphinxcontrib/confluencebuilder/storage/translator.py
> +            self.body.append(self._build_ac_param(node, 'theme', theme))
I think I was trying to follow what appeared to be an existing convention (e.g. with `title` and `firstline`), but I'm happy to simplify per your suggestion (as I don't see a need to leave `theme` exposed).

2023-05-27 21:54 UTC, bpandola commented on tests/unit-tests/test_sphinx_codeblock.py
> +        config.confluence_code_block_theme = theme
Thanks.  I looked, but clearly not hard enough, for a similar example.  I appreciate you pointing it out.

2023-05-28 02:12 UTC, bpandola commented
@jdknight Thanks for the review.  I think I've addressed everything you mentioned.  I'll keep adding commits until you approve, but let me know if I need to squash into one commit (with the DCO sign-off-by) before you merge.

2023-05-28 14:24 UTC, jdknight commented
@bpandola, thanks for addressing each point (and more). It looks great. Once the DCO is addressed, we should be able to merge this in.

2023-05-28 22:27 UTC, bpandola commented
@jdknight DCO addressed.

2023-05-29 01:29 UTC, jdknight approved these changes

2023-05-29 01:29 UTC, merged